/* eslint-disable @next/next/no-page-custom-font */

import useSWR from "swr";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { Selector } from "../components/selector";
import TablePagination from "@mui/material/TablePagination";
import Skeleton from "@mui/material/Skeleton";
import Box from "@mui/material/Box";

import {
  parseParams,
  getReviewsParams,
  paginationFetcher,
  getMakeOptions,
} from "../lib/api";

import useStore from "../state";

const pageSelector = (state) => state.page;
const rowsPerPageSelector = (state) => state.rowsPerPage;
const reviewsUrlSelector = (state) => state.reviewsUrl;
const selectedMakeSelector = (state) => state.selectedMake;
const selectedModelSelector = (state) => state.selectedModel;
const modelOptionsSelector = (state) => state.modelOptions;
const setPageSelector = (state) => state.setPage;
const setRowsPerPageSelector = (state) => state.setRowsPerPage;
const setMakeSelector = (state) => state.setSelectedMake;
const setModelSelector = (state) => state.setSelectedModel;

export default function Home({ initialData, allMakes }) {
  const page = useStore(pageSelector);
  const rowsPerPage = useStore(rowsPerPageSelector);
  const reviewsUrl = useStore(reviewsUrlSelector);
  const selectedMake = useStore(selectedMakeSelector);
  const selectedModel = useStore(selectedModelSelector);
  const modelOptions = useStore(modelOptionsSelector);
  const setPage = useStore(setPageSelector);
  const setRowsPerPage = useStore(setRowsPerPageSelector);
  const setMake = useStore(setMakeSelector);
  const setModel = useStore(setModelSelector);

  const { data, isValidating } = useSWR(reviewsUrl, paginationFetcher, {
    fallbackData: initialData,
  });

  const handleChangePage = (event, newPage) => {
    setPage(newPage);
  };

  const handleChangeRowsPerPage = (event) => {
    setRowsPerPage(parseInt(event.target.value, 10));
  };

  const handleMakeChange = (event) => {
    setMake(event.target.value);
  };

  const handleModelChange = (event) => {
    setModel(event.target.value);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
        />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
        />
      </Head>

      <main className={styles.main}>
        <div className={styles.selectors}>
          <Selector
            label="make"
            value={selectedMake}
            handleChange={handleMakeChange}
            options={allMakes}
          />
          <Selector
            label="model"
            value={selectedModel}
            handleChange={handleModelChange}
            options={modelOptions}
            disabled={!selectedMake}
          />
        </div>

        <Box>
          {isValidating ? (
            Array.from({ length: rowsPerPage }, (_, i) => (
              <Skeleton animation="wave" key={i} variant="text" width={300} />
            ))
          ) : (
            <ul className={styles.list}>
              {data.stories.map((s) => (
                <li key={s.id}>{s.name}</li>
              ))}
            </ul>
          )}
        </Box>

        <TablePagination
          component="div"
          count={data.total}
          page={page}
          onPageChange={handleChangePage}
          rowsPerPage={rowsPerPage}
          onRowsPerPageChange={handleChangeRowsPerPage}
        />
      </main>
    </div>
  );
}

export async function getStaticProps({ preview = false }) {
  const params = { ...getReviewsParams({ preview }), page: 1, per_page: 25 };
  const initialKey = `https://api.storyblok.com/v2/cdn/stories/${parseParams(
    params
  )}`;

  const initialData = await paginationFetcher(initialKey);
  const allMakes = await getMakeOptions();

  return {
    props: {
      initialData,
      allMakes,
    },
  };
}
